web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  environment:
    - YOURLS_DB_USER=root
    - YOURLS_DB_PASS=coolpassword
    - YOURLS_DB_NAME=yourls
    - YOURLS_DB_HOST=db
    - YOURLS_DEBUG=false
    - YOURLS_USERS=default:default
    - YOURLS_SITE=http://set-this-or-the-site-doesnt-work.com/my-blog.asp
db:
  ports:
    - "3306:3306"
  image: mysql:5.6.26
  environment:
    - MYSQL_ROOT_PASSWORD=coolpassword
    - MYSQL_DATABASE=yourls
